/*
 * Copyright 2024 balena.io and FireRat666
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

import * as electron from 'electron';
import * as remoteMain from '@electron/remote/main';
import Store from 'electron-store';
import contextMenu from 'electron-context-menu';
import { promises as fs } from 'fs';
import { platform } from 'os';
import * as path from 'path';

import './app/i18n';

import * as EXIT_CODES from '../shared/exit-codes';
import * as settings from './app/models/settings';
import { buildWindowMenu } from './menu';
import * as i18n from 'i18next';

const customProtocol = 'etcher';
const scheme = `${customProtocol}://`;
let mainWindow: any = null;

remoteMain.initialize();

// Write renderer console output to the terminal when launched from a command line
electron.ipcMain.on(
	'renderer-console',
	(_event, level: string, text: string) => {
		const line = `[renderer] ${text}\n`;
		if (level === 'error' || level === 'warn') {
			process.stderr.write(line);
		} else {
			process.stdout.write(line);
		}
	},
);

// A reference to the active power save blocker, preventing the system
// from going to sleep while flashing
let sleepBlockerId: number | undefined;

/**
 * @summary Prevent the system from going to sleep while flashing
 *
 * @description
 * Uses `prevent-display-sleep` so the screen stays on and the system
 * does not go to sleep on Windows, macOS and Linux.
 */
function startSleepBlocker() {
	if (sleepBlockerId !== undefined) {
		return;
	}
	sleepBlockerId = electron.powerSaveBlocker.start('prevent-display-sleep');
	console.info('Preventing the system from sleeping while flashing');
}

/**
 * @summary Stop preventing the system from going to sleep
 */
function stopSleepBlocker() {
	if (sleepBlockerId === undefined) {
		return;
	}
	electron.powerSaveBlocker.stop(sleepBlockerId);
	sleepBlockerId = undefined;
	console.info('Re-enabled system sleep');
}

// The renderer asks to disable the screensaver and prevent system sleep
// while flashing, and to re-enable it afterwards
electron.ipcMain.on('disable-screensaver', startSleepBlocker);
electron.ipcMain.on('enable-screensaver', stopSleepBlocker);

const store = new Store();

// Globally export what OS we are on
const isLinux = process.platform === 'linux';
const isWin = process.platform === 'win32';
const isMac = process.platform === 'darwin';

async function checkForUpdates() {
	console.info('Auto-Updates disabled for this build');
}

function logMainProcessException(error: any) {
	console.error(error);
}

// Log uncaught main process exceptions locally; no remote error reporting
process.on('uncaughtException', logMainProcessException);

async function isFile(filePath: string): Promise<boolean> {
	try {
		const stat = await fs.stat(filePath);
		return stat.isFile();
	} catch {
		// noop
	}
	return false;
}

async function getCommandLineURL(argv: string[]): Promise<string | undefined> {
	argv = argv.slice(electron.app.isPackaged ? 1 : 2);
	if (argv.length) {
		const value = argv[argv.length - 1];
		// Take into account electron arguments
		if (value.startsWith('--')) {
			return;
		}
		// https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder
		if (platform() === 'darwin' && value.startsWith('-psn_')) {
			return;
		}
		if (
			!value.startsWith('http://') &&
			!value.startsWith('https://') &&
			!value.startsWith(scheme) &&
			!(await isFile(value))
		) {
			return;
		}
		return value;
	}
	return undefined;
}

const sourceSelectorReady = new Promise((resolve) => {
	electron.ipcMain.on('source-selector-ready', resolve);
});

async function selectImageURL(url?: string) {
	// 'data:,' is the default chromedriver url that is passed as last argument when running spectron tests
	if (url !== undefined && url !== 'data:,') {
		url = url.replace(/\/$/, ''); // on windows the url ends with an extra slash
		url = url.startsWith(scheme) ? url.slice(scheme.length) : url;
		await sourceSelectorReady;
		electron.BrowserWindow.getAllWindows().forEach((window) => {
			window.webContents.send('select-image', url);
		});
	}
}

// This will catch clicks on links such as <a href="etcher://...">Open in Etcher</a>
// We need to listen to the event before everything else otherwise the event won't be fired
electron.app.on('open-url', async (event, data) => {
	event.preventDefault();
	await selectImageURL(data);
});

async function createMainWindow() {
	const fullscreen = Boolean(await settings.get('fullscreen'));
	const defaultWidth = settings.DEFAULT_WIDTH;
	const defaultHeight = settings.DEFAULT_HEIGHT;
	const iconPath = isWin
		? path.join(__dirname, 'media', 'icon.ico')
		: path.join(__dirname, 'media', 'icon64.png');
	let width = defaultWidth;
	let height = defaultHeight;
	if (fullscreen) {
		({ width, height } = electron.screen.getPrimaryDisplay().bounds);
	}
	mainWindow = new electron.BrowserWindow({
		width,
		height,
		minWidth: 632,
		minHeight: 400,
		frame: !fullscreen,
		useContentSize: true,
		show: false,
		resizable: true,
		maximizable: true,
		fullscreen,
		fullscreenable: fullscreen,
		kiosk: fullscreen,
		autoHideMenuBar: false,
		titleBarStyle: 'hiddenInset',
		icon: iconPath,
		darkTheme: true,
		webPreferences: {
			backgroundThrottling: false,
			nodeIntegration: true,
			contextIsolation: false,
			devTools: true,
			experimentalFeatures: true,
			webviewTag: true,
			zoomFactor: width / defaultWidth,
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
		},
	});

	electron.app.setAsDefaultProtocolClient(customProtocol);

	electron.nativeTheme.themeSource = 'dark';

	// mainWindow.setFullScreen(true);

	const showWindow = () => {
		if (mainWindow && !mainWindow.isVisible()) {
			mainWindow.webContents.setZoomFactor(width / defaultWidth);
			mainWindow.show();
		}
	};

	// Prevent flash of white when starting the application
	mainWindow.once('ready-to-show', () => {
		console.timeEnd('ready-to-show');
		showWindow();
	});

	// Fallback for Linux VMs / software rendering where ready-to-show may be delayed or missed
	setTimeout(showWindow, 1500);

	// Prevent external resources from being loaded (like images)
	// when dropping them on the WebView.
	// See https://github.com/electron/electron/issues/5919
	mainWindow.webContents.on('will-navigate', (event: any) => {
		event.preventDefault();
	});

	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	const page = mainWindow.webContents;
	remoteMain.enable(page);

	page.once('did-frame-finish-load', async () => {
		checkForUpdates();
	});

	// Stop preventing the system from sleeping if the renderer crashes
	// or the window is closed while flashing
	mainWindow.webContents.on('render-process-gone', stopSleepBlocker);
	mainWindow.on('closed', stopSleepBlocker);

	mainWindow.on('close', () => {
		if (mainWindow) {
			store.set('windowDetails', {
				position: mainWindow.getPosition(),
			});
			console.info('Saved windowDetails');
		} else {
			console.error(
				'Error: mainWindow was not defined while trying to save windowDetails.',
			);
		}
	});

	const windowDetails = store.get('windowDetails') as
		{ position: [number, number] } | undefined;

	if (windowDetails) {
		mainWindow.setPosition(
			windowDetails.position[0],
			windowDetails.position[1],
		);
	} else {
		console.warn('No windowDetails');
	}

	return mainWindow;
}

electron.app.on('edit-config-file', () => {
	if (isLinux) {
		console.info(
			'Note that JSON must be a recognized file type for the OS to open the config.json file.',
		);
		console.warn(
			'On Linux, a default text editor for handling JSON files must also be present and configured correctly.',
		);
		store.openInEditor();
		return;
	} else {
		console.info(
			'Note that JSON must be a recognized file type \n for the OS to open the config.json file.',
		);
		store.openInEditor();
	}
});

electron.app.on('window-all-closed', () => {
	if (!isMac) {
		console.warn('mainWindow.close()');
		electron.app.quit();
	} else {
		console.info('Not keeping dock alive even though this is MacOS');
		console.warn('mainWindow.close()');
		electron.app.quit();
	}
});

// Sending a `SIGINT` (e.g: Ctrl-C) to an Electron app that registers
// a `beforeunload` window event handler results in a disconnected white
// browser window in GNU/Linux and macOS.
// The `before-quit` Electron event is triggered in `SIGINT`, so we can
// make use of it to ensure the browser window is completely destroyed.
// See https://github.com/electron/electron/issues/5273
electron.app.on('before-quit', () => {
	stopSleepBlocker();
	console.info('Etcher Privacy is quitting now');
	electron.app.releaseSingleInstanceLock();
	process.exit(EXIT_CODES.SUCCESS);
});

electron.app.on('relaunch', () => {
	console.warn('Restarting App...');
	if (mainWindow) {
		store.set('windowDetails', {
			position: mainWindow.getPosition(),
		});
		console.info('Saved windowDetails');
	} else {
		console.error(
			'Error: mainWindow was not defined while trying to save windowDetails.',
		);
	}
});

// this is replaced at build-time with the path to helper binary,
// relative to the app resources directory.
declare const ETCHER_UTIL_BIN_PATH: string;

electron.ipcMain.handle('get-util-path', () => {
	if (process.env.NODE_ENV === 'development') {
		// In development there is no "app bundle" and we're working directly with
		// artifacts from the "out" directory, where this value point to.
		return ETCHER_UTIL_BIN_PATH;
	}
	// In any other case, resolve the helper relative to resources path.
	return path.resolve(process.resourcesPath, ETCHER_UTIL_BIN_PATH);
});

contextMenu({
	// Chromium context menu defaults
	showSelectAll: true,
	showCopyImage: true,
	showCopyImageAddress: true,
	showSaveImageAs: true,
	showCopyVideoAddress: true,
	showSaveVideoAs: true,
	showCopyLink: true,
	showSaveLinkAs: true,
	showInspectElement: true,
	showLookUpSelection: true,
	showSearchWithGoogle: false,
	prepend: (_defaultActions, parameters) => [
		{
			label: 'Open Link in New Window',
			// Only show it when right-clicking a link
			visible: parameters.linkURL.trim().length > 0,
			click: () => {
				const toURL = parameters.linkURL;
				const linkWin = new electron.BrowserWindow({
					title: 'New Window',
					width: 1024,
					height: 700,
					useContentSize: true,
					darkTheme: true,
					webPreferences: {
						nodeIntegration: false,
						nodeIntegrationInWorker: false,
						experimentalFeatures: true,
						devTools: true,
					},
				});
				linkWin.loadURL(toURL);
				console.info('Opened Link in New Window');
			},
		},
		{
			label: 'Search with Google',
			// Only show it when right-clicking text
			visible: parameters.selectionText.trim().length > 0,
			click: () => {
				const queryURL = `${encodeURIComponent(parameters.selectionText)}`;
				const searchURL = `https://google.com/search?q=${encodeURIComponent(parameters.selectionText)}`;
				const searchWin = new electron.BrowserWindow({
					width: 1024,
					height: 700,
					useContentSize: true,
					darkTheme: true,
					webPreferences: {
						nodeIntegration: false,
						nodeIntegrationInWorker: false,
						experimentalFeatures: true,
						devTools: true,
					},
				});
				searchWin.loadURL(searchURL);
				console.info('Searched for "' + queryURL + '" on Google');
			},
		},
		{
			label: 'Open Image in New Window',
			// Only show it when right-clicking an image
			visible: parameters.mediaType === 'image',
			click: () => {
				const imgURL = parameters.srcURL;
				const imgTitle = imgURL.substring(imgURL.lastIndexOf('/') + 1);
				const imgWin = new electron.BrowserWindow({
					title: imgTitle,
					useContentSize: true,
					darkTheme: true,
					webPreferences: {
						nodeIntegration: false,
						nodeIntegrationInWorker: false,
						experimentalFeatures: true,
						devTools: true,
					},
				});
				imgWin.loadURL(imgURL);
				console.info('Opened Image in New Window');
			},
		},
		{
			label: 'Open Video in New Window',
			// Only show it when right-clicking a video
			visible: parameters.mediaType === 'video',
			click: () => {
				const vidURL = parameters.srcURL;
				const vidTitle = vidURL.substring(vidURL.lastIndexOf('/') + 1);
				const vidWin = new electron.BrowserWindow({
					title: vidTitle,
					useContentSize: true,
					darkTheme: true,
					webPreferences: {
						nodeIntegration: false,
						nodeIntegrationInWorker: false,
						experimentalFeatures: true,
						devTools: true,
					},
				});
				vidWin.loadURL(vidURL);
				console.info('Popped out Video');
			},
		},
	],
});

async function main(): Promise<void> {
	if (!electron.app.requestSingleInstanceLock()) {
		electron.app.quit();
	} else {
		await electron.app.whenReady();
		electron.app.commandLine.appendSwitch('ignore-gpu-blocklist');
		const window = await createMainWindow();
		electron.app.on('second-instance', async (_event, argv) => {
			if (window.isMinimized()) {
				window.restore();
			}
			window.focus();
			await selectImageURL(await getCommandLineURL(argv));
		});
		await selectImageURL(await getCommandLineURL(process.argv));

		electron.ipcMain.on('change-lng', function (_event, args) {
			i18n.changeLanguage(args, () => {
				console.log('Language changed to: ' + args);
			});
			if (mainWindow != null) {
				buildWindowMenu(mainWindow);
			} else {
				console.log('Build menu failed. ');
			}
		});

		electron.ipcMain.on('webview-dom-ready', (_, id) => {
			const webview = electron.webContents.fromId(id);

			// Open link in browser if it's opened as a 'foreground-tab'
			webview!.setWindowOpenHandler((event) => {
				const url = new URL(event.url);
				if (
					(url.protocol === 'http:' || url.protocol === 'https:') &&
					event.disposition === 'foreground-tab' &&
					// Don't open links if they're disabled by the env var
					!settings.getSync('disableExternalLinks')
				) {
					electron.shell.openExternal(url.href);
				}
				return { action: 'deny' };
			});
		});
	}
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// tslint:disable-next-line:no-var-requires
if (require('electron-squirrel-startup')) {
	electron.app.quit();
}

main();

console.time('ready-to-show');
