name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]
    tags: ['v*']

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN || secrets.GITHUB_TOKEN }}
    with:
      custom_test_matrix: >
        {
          "os": [
            ["ubuntu-24.04"],
            ["windows-2025"],
            ["macos-15"]
          ]
        }
      custom_publish_matrix: >
        {
          "os": [
            ["ubuntu-24.04"],
            ["windows-2025"],
            ["macos-15"]
          ]
        }
      github_prerelease: true
